version: "3.7"
services:
  docker-registry-host:
    image: registry:2.8.1
    ports:
      - 5000:5000
    environment:
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/registry.password
      REGISTRY_HTTP_DEBUG_ADDR: IP_REGISTRY:5001
      REGISTRY_HTTP_DEBUG_PROMETHEUS_ENABLED: "true"
      REGISTRY_HTTP_DEBUG_PROMETHEUS_PATH: /metrics
    volumes:
      - ./registry-data:/var/lib/registry
      - ./auth:/auth
    networks:
      - docker-registry
    restart: always
  
  debug:
    addr: localhost:5001
    prometheus:
      enabled: true
      path: /metrics

  docker-registry-host-web-ui:
    image: konradkleine/docker-registry-frontend:v2
    environment:
      ENV_DOCKER_REGISTRY_HOST: IP_REGISTRY
      ENV_DOCKER_REGISTRY_PORT: 5000
    ports:
      - 8080:80
    networks:
      - docker-registry
    restart: always

networks:
  docker-registry:

# version: "3.7"
# services:
#   docker-registry-host:
#     image: registry:2.8.1
#     ports:
#       - "5000:5000"
#       - "5001:5001"
#     environment:
#       REGISTRY_AUTH: htpasswd
#       REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
#       REGISTRY_AUTH_HTPASSWD_PATH: /auth/registry.password
#       REGISTRY_HTTP_DEBUG_ADDR: localhost:5001
#       REGISTRY_HTTP_DEBUG_PROMETHEUS_ENABLED: "true"
#       REGISTRY_HTTP_DEBUG_PROMETHEUS_PATH: /metrics
#     volumes:
#       - ./registry-data:/var/lib/registry
#       - ./auth:/auth
# #    networks:
# #      - docker-registry
#     restart: always

#   docker-registry-host-web-ui:
#     image: konradkleine/docker-registry-frontend:v2
#     environment:
#       ENV_DOCKER_REGISTRY_HOST: 192.168.23.162
#       ENV_DOCKER_REGISTRY_PORT: 5000
#     ports:
#       - 8080:80
# #    networks:
# #      - docker-registry
#     restart: always

# #networks:
# #  docker-registry: